version: '3.8'

services:
  database:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_VERSION=13
        - DB_NAME=${DB_NAME:-migrationdb}
        - DB_USER=${DB_USER:-dbadmin}
        - DB_PASSWORD=${DB_PASSWORD:-securepassword}
        - MIGRATION_STRATEGY=${MIGRATION_STRATEGY:-rolling}
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/migrations:/liquibase/changelog
      - ./src/scripts:/scripts

  migration:
    image: liquibase/liquibase
    volumes:
      - ./src/migrations:/liquibase/changelog
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://database:5432/${DB_NAME}
      - LIQUIBASE_COMMAND_USERNAME=${DB_USER}
      - LIQUIBASE_COMMAND_PASSWORD=${DB_PASSWORD}
    depends_on:
      - database

volumes:
  postgres_data: