- hosts: database_servers
  become: yes
  vars:
    postgres_version: 13
    db_name: maindb
    db_user: dbadmin

  tasks:
    - name: Install PostgreSQL
      apt:
        name: 
          - postgresql-{{ postgres_version }}
          - postgresql-contrib
        state: present

    - name: Create database
      postgresql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create database user
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        state: present
        login_user: postgres

    - name: Configure PostgreSQL for replication
      template:
        src: templates/postgresql.conf.j2
        dest: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf